name: deploy
on:
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: python -m pip install --upgrade pip nox tomli

    - name: Download, test and publish package
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: nox --session pypi --stop-on-first-error
